package events

import mock "github.com/stretchr/testify/mock"

// MockEventBus is an autogenerated mock type for the EventBus type
type MockEventBus struct {
	mock.Mock
}

// HandleEvent provides a mock function with given fields: handler
func (_m *MockEventBus) HandleEvent(handler func(*Event) error) error {
	ret := _m.Called(handler)

	var r0 error
	if rf, ok := ret.Get(0).(func(func(*Event) error) error); ok {
		r0 = rf(handler)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Send provides a mock function with given fields: ev
func (_m *MockEventBus) Send(ev *Event) error {
	ret := _m.Called(ev)

	var r0 error
	if rf, ok := ret.Get(0).(func(*Event) error); ok {
		r0 = rf(ev)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
