package messagebus

import mock "github.com/stretchr/testify/mock"

// MockMessageBus is an autogenerated mock type for the MessageBus type
type MockMessageBus struct {
	mock.Mock
}

// HandleMessage provides a mock function with given fields: handler
func (_m *MockMessageBus) HandleMessage(handler func([]byte, Message) error) error {
	ret := _m.Called(handler)

	var r0 error
	if rf, ok := ret.Get(0).(func(func([]byte, Message) error) error); ok {
		r0 = rf(handler)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Send provides a mock function with given fields: payload, peerIDs
func (_m *MockMessageBus) Send(payload *Payload, peerIDs []string) error {
	ret := _m.Called(payload, peerIDs)

	var r0 error
	if rf, ok := ret.Get(0).(func(*Payload, []string) error); ok {
		r0 = rf(payload, peerIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
