// Code generated by protoc-gen-go.
// source: messagebus.proto
// DO NOT EDIT!

/*
Package messagebus is a generated protocol buffer package.

It is generated from these files:
	messagebus.proto

It has these top-level messages:
	Payload
	Message
	Envelope
*/
package messagebus

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Payload struct {
	Creator string `protobuf:"bytes,1,opt,name=creator" json:"creator,omitempty"`
	Type    string `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	Data    []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *Payload) Reset()                    { *m = Payload{} }
func (m *Payload) String() string            { return proto.CompactTextString(m) }
func (*Payload) ProtoMessage()               {}
func (*Payload) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Payload) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *Payload) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Payload) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Message struct {
	Payload   []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Message) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Message) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type Envelope struct {
	Message []byte `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Hash    []byte `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (m *Envelope) Reset()                    { *m = Envelope{} }
func (m *Envelope) String() string            { return proto.CompactTextString(m) }
func (*Envelope) ProtoMessage()               {}
func (*Envelope) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Envelope) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *Envelope) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func init() {
	proto.RegisterType((*Payload)(nil), "messagebus.Payload")
	proto.RegisterType((*Message)(nil), "messagebus.Message")
	proto.RegisterType((*Envelope)(nil), "messagebus.Envelope")
}

func init() { proto.RegisterFile("messagebus.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 175 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x44, 0xcf, 0x31, 0x0b, 0xc2, 0x30,
	0x10, 0x05, 0x60, 0xaa, 0xd2, 0xda, 0x23, 0x53, 0xa6, 0x0c, 0x0e, 0xa5, 0x53, 0x27, 0x17, 0x17,
	0x57, 0x07, 0x27, 0x11, 0x24, 0xff, 0xe0, 0xb4, 0x47, 0x2b, 0xd4, 0x26, 0x24, 0xb1, 0xd0, 0x7f,
	0x2f, 0xbd, 0x34, 0xb8, 0xbd, 0xf7, 0x20, 0x5f, 0x38, 0x10, 0x34, 0xd1, 0x18, 0xfc, 0xd1, 0x3a,
	0x13, 0x8c, 0xcc, 0x63, 0xab, 0x6f, 0x50, 0x3c, 0x70, 0x1e, 0x0c, 0xb6, 0x52, 0x41, 0xf1, 0x72,
	0x84, 0xc1, 0x38, 0x95, 0x55, 0x59, 0x53, 0xea, 0x54, 0xa5, 0x84, 0x5d, 0x98, 0x2d, 0xa9, 0x0d,
	0xcf, 0x9c, 0x97, 0xad, 0xc5, 0x80, 0x6a, 0x5b, 0x65, 0x8d, 0xd0, 0x9c, 0xeb, 0x0b, 0x14, 0x77,
	0xf2, 0x1e, 0x3b, 0x5a, 0x30, 0x1b, 0x5d, 0xc6, 0x84, 0x4e, 0x55, 0x1e, 0xa0, 0xf4, 0xef, 0x6e,
	0xc4, 0xf0, 0x75, 0x51, 0x14, 0xfa, 0x3f, 0xd4, 0x67, 0xd8, 0x5f, 0xc7, 0x89, 0x06, 0x63, 0xd9,
	0xf8, 0x44, 0x2e, 0x19, 0x6b, 0x5d, 0x3e, 0xef, 0xd1, 0xf7, 0xeb, 0x73, 0xce, 0xcf, 0x9c, 0x0f,
	0x3b, 0xfd, 0x02, 0x00, 0x00, 0xff, 0xff, 0xe2, 0x54, 0xed, 0xa9, 0xe8, 0x00, 0x00, 0x00,
}
